harness/helm-charts

src/harness/values.yaml
Documented just about everything in the Harness helm charts. Please re-run helm-docs to populate the values in the README
=> helm chart documentation overhaul

src/generate-image-list.sh, src/harness/override-demo.yaml, src/harness/override-prod.yaml, src/harness/values.yaml
1. Added toggle to choose between the delegate maximal or minimal image
2. Updated the generate-image-list.sh to include the minimal images in the images.txt
=> SMP-1130: Package delegate minimal as part of the SMP release

src/harness/README.md, src/harness/README.md.gotmpl
Update readme: fix links, fix typo, add release notes link
=> Update readme: fix links, fix typo, add release notes link

src/generate-image.yaml, src/harness/images.txt
Added these fields to generate-image.yaml file
lwd:
enabled: true
autocud:
enabled: true
ccm:
clickhouse:
enabled: true
This will include CCM related images to images.txt
Tested changes locally. Added image names in images.txt
=> Added CCM related images to images.txt

src/airgap_input.txt, src/create_airgap_module_images.sh
Details here: https://harness.atlassian.net/l/cp/kiCeAGSo
=> [SMP-1429] Airgap tool to create module specific images.txt

src/harness/README.md
Update README.md for 0.7.0, 79421
=> Update README.md for 0.7.0, 79421

src/create_airgap_module_images.sh
Update script to address these validations:
print each file name once file is created
Make sure module images files are not empty
check if any image file name that is not read from main images.txt
=> Added error validation and exit codes

src/harness/README.md
=> Update README.md for 0.7.1 79422

src/generate-image.yaml, src/harness/Chart.yaml, src/harness/override-demo.yaml, src/harness/override-prod.yaml, src/harness/templates/destinationrule.yaml, src/harness/values.yaml
Reverts harness/helm-charts#314
=> Revert "feat: [CET-1354]: Initial CET commit. "

src/generate-image.yaml, src/harness/Chart.yaml, src/harness/override-demo.yaml, src/harness/override-prod.yaml, src/harness/templates/destinationrule.yaml, src/harness/values.yaml
=> feat: [CET-1354]: Initial CET commit

src/generate-image-list.sh
Tracking Jira: https://harness.atlassian.net/browse/SMP-1432
Updating generate-images-list.sh script to accept arguments for specifying the following to support generation of images.txt in pipelines that do not follow the required folder structure.
1. Path to generate-image.yaml
2. Path to output directory for images.txt
3. Harness Directory
Note: These changes are compatible with previous usage
=> SMP-1432: update images list generation script to accept runtime arguments

src/harness/README.md
Update helm upgrade command in readme
=> [SMP-1786] [DOC-3597] Update helm upgrade command in readme

src/harness/README.md, src/harness/README.md.gotmpl
=> Update README.md for 0.8.2

src/harness/README.md
Update README for patch release 0.8.3
=> Update README for patch release 0.8.3

src/airgap/create-airgap-bundle.sh
Added error validation in case docker pull fails with network error or any other error.
For any error script will abort and will not create any bundle for other modules as well.
Testing:
output snippet :
swapnildeshmukh@Swapnil Deshmukh airgap % ./create-airgap-bundle.sh 
docker.io/harness/gitops-agent:v0.56.7
Image pull success: docker.io/harness/gitops-agent:v0.56.7
Error response from daemon: unauthorized: access to the requested resource is not authorized
Error Image pull failed: quay.io/argoproj/arocd:v2.7.8
Error Failed background task with PID: 33266
=> Error validation airgap during bundle creation 

src/harness/README.md
Update README for the 0.9.1 patch release
=> Update README for the 0.9.1 patch release

src/harness/override-demo.yaml, src/harness/override-prod.yaml
Initially causing:
after running migrate script, the error is resolved.
Tested templating locally.
=> fix:[SMP-2121]: Fix for invalidation errors in override files

src/harness/override-demo.yaml, src/harness/override-prod.yaml, src/harness/values.yaml
Added the newly added common annotations and common labels settings into the override-demo and override-prod manifest files.
=> feat: [SMP-1216]: added common annotations and labels setting in the override files

src/harness/README.md
=> Update README for 0.9.2

src/harness/README.md
=> Update README for 0.9.3

src/harness/monitoring.yaml
The monitoring.yaml file in the helm-chart was outdated. The file is updated here.
=> [SMP-2220]: Update monitoring override

src/harness/monitoring.yaml
* SMP-2220 Update monitoring override
=> [SMP-2220]: Update monitoring override (#442)

src/harness/override-perf-ci-cd-ff.yaml
platform.redis migrated to bootstrap.database.redis
=> [SMP-2220]: Update migrated override-perf-ci-cd-ff.yaml

src/harness/README.md, src/harness/templates/_validation.tpl, src/harness/values.yaml
Issue observed in 3.8.2 and 3.9.4 charts
=> fix: SMP-2252: Support invalidation script for 3.8.2 and 3.9.4 helm versions

src/airgap/airgap_input.txt
Added 2 new images to input list file
=> Updated airgap input list with 2 new images

src/harness/README.md
=> Update README.md for 0.10.0

src/airgap/create-airgap-bundle.sh
Updated create bundle script to specify module name to parallelize bundle creation in pipeline:
Tested in airgap generation pipeline.
=> Added an option to specify individual bundle creation

src/harness/README.md
=> Update README.md for 0.12.0

src/harness/values.yaml
Enabling file logging for supported services as the default
=> feat: [PL-42058]: Enable file logging as the default

src/harness/README.md
=> Update README.md for 0.13.4

src/harness/override-demo.yaml, src/harness/override-prod.yaml, src/harness/values.yaml, src/modules/platform/Chart.yaml
changing the condition to install change data capture currently is it on ng flag now moving to separate flag to cdc
=> changing the condition to install change data capture

src/harness/README.md
=> Update README.md for 0.14.3

support-bundle-manifests/module-wise/support-bundle-ccm.yaml, support-bundle-manifests/module-wise/support-bundle-cd.yaml, support-bundle-manifests/module-wise/support-bundle-cet.yaml, support-bundle-manifests/module-wise/support-bundle-chaos.yaml, support-bundle-manifests/module-wise/support-bundle-ci.yaml, support-bundle-manifests/module-wise/support-bundle-ff.yaml, support-bundle-manifests/module-wise/support-bundle-platform.yaml, support-bundle-manifests/module-wise/support-bundle-srm.yaml, support-bundle-manifests/module-wise/support-bundle-ssca.yaml, support-bundle-manifests/module-wise/support-bundle-sto.yaml, support-bundle-manifests/support-bundle-all.yaml
Added logs collection for databases
=> feat: [PL-47949]: Added log collection for databases

support-bundle-manifests/module-wise/support-bundle-ccm.yaml, support-bundle-manifests/module-wise/support-bundle-cd.yaml, support-bundle-manifests/module-wise/support-bundle-cet.yaml, support-bundle-manifests/module-wise/support-bundle-chaos.yaml, support-bundle-manifests/module-wise/support-bundle-ci.yaml, support-bundle-manifests/module-wise/support-bundle-ff.yaml, support-bundle-manifests/module-wise/support-bundle-platform.yaml, support-bundle-manifests/module-wise/support-bundle-srm.yaml, support-bundle-manifests/module-wise/support-bundle-ssca.yaml, support-bundle-manifests/module-wise/support-bundle-sto.yaml, support-bundle-manifests/support-bundle-all.yaml
Increase timeout from 30s to 300s
=> fix: [PL-48365]: Increase timeout for collectors

src/harness/README.md
=> Update README.md for 0.14.4

src/harness/README.md
=> Update README.md for 0.14.5

src/harness/README.md
=> Update README.md for 0.14.6

support-bundle-manifests/README.md, support-bundle-manifests/scripts/windows.ps1
Added windows script to add support for support bundle manifest generation for windows users
=> feat: [PL-48130]: Added windows script

src/harness/README.md
Update README.md for 0.15.1 patch release
=> Update README.md for 0.15.1 patch release

src/harness/README.md
=> Update README.md for 0.16.0

src/harness/README.md
=> Update README for 0.16.1

src/harness/README.md
Update README.md for 0.16.2 patch release
=> chore: [PL-51530] Update README for 0.16.2 patch release

src/harness/README.md
chore: [PL-51498] Update README for 0.17.0 release
[PL-51498]: https://harness.atlassian.net/browse/PL-51498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [PL-51498] Update README for 0.17.0 release

src/harness/override-prod.yaml, src/harness/values.yaml
* [PL-51635]: Updating OPA flag to true
* Update override-prod.yaml to remove opa
[PL-51635]: https://harness.atlassian.net/browse/PL-51635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PL-51635]: Updating OPA flag to true (#647)

src/harness/README.md
hore: [PL-51751] Update README for 0.17.1 patch release
[PL-51751]: https://harness.atlassian.net/browse/PL-51751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [PL-51751] Update README for 0.17.1 patch release

tests/statefulset_test.yaml
fix: [PL-51814]: Fix stateful set test to include known values.
[PL-51814]: https://harness.atlassian.net/browse/PL-51814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [PL-51814]: Fix stateful set test to include known values.

src/harness/Chart.yaml, src/modules/ccm/Chart.yaml, src/modules/cd/Chart.yaml, src/modules/chaos/Chart.yaml, src/modules/ci/Chart.yaml, src/modules/db-devops/Chart.yaml, src/modules/ff/Chart.yaml, src/modules/platform/Chart.yaml, src/modules/srm/Chart.yaml, src/modules/ssca/Chart.yaml, src/modules/sto/Chart.yaml
This reverts commit db9c0641948f55d3ead85ec6d1aa3510c5cb3be6.
=> Revert "increment umbrella chart minor version"

src/airgap/airgap_input.txt, src/airgap/validate_airgap.sh
Image changes based on diff for 0.20.0 and 0.21.0 images.txt (https://www.diffchecker.com/Ie3o5cwi/)
and changes done in 0.20.0 release branch not merged to main (https://github.com/harness/helm-charts/pull/721/files#diff-57a86107ab3a4ffa1b80dc8cfab440134bb243874446e9d15f62c1b851a04c6c)
=> updated images in airgap input script

tests/hpa_test.yaml
UT for hpa that works with hpa common function
=> feat: [PL-58047]: added uts for hpa

src/harness/templates/mongo-preupgradejob.yaml, src/harness/values.yaml
Fix FCV upgrade job to use correct condition
add support for nodeSelector, tolerations, affinity.
=> Fix FCV upgrade job to use correct condition

src/harness/scripts/update-pvc.sh
Currently the customers have to follow a document https://developer.harness.io/docs/self-managed-enterprise-edition/advanced-configurations/increase-pv-size-statefulsets step by step to update PVC size. 
Maintaining the document and making sure the customer follows it correctly is difficult. 
This script aims to automate the process for all databases.
=> feat: [PL-58176]: Script to automate pvc size increase

tests/role_test.yaml
Due to this PR -https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/module/code/orgs/HarnessHCRInternalUAT/projects/Harness_Code/repos/harness-core/pulls/70996/checks?uid=Helm_Unit_Tests-Run_Tests
The helm tests are failing.
Commented out the failed test case until it is finalized whether we are making same changes to all the services or need to support both the cases. Will then update the tests.
=> fix: [PL-10000]: Disable 1 test in role chart

plugin-build-tool.json, src/harness/Chart.yaml
This reverts commit 23f958b7fa2dfc6a8573edf669c5cf461a772d8a.
=> Revert "increment umbrella chart patch version"

src/harness/Chart.yaml
Reverts harness/helm-charts#943
=> Revert "feat: [PL-61236]: increment umbrella chart patch version for release/0.26.9"

src/harness/Chart.yaml, src/modules/ccm/Chart.yaml, src/modules/cd/Chart.yaml, src/modules/chaos/Chart.yaml, src/modules/ci/Chart.yaml, src/modules/code/Chart.yaml, src/modules/db-devops/Chart.yaml, src/modules/ff/Chart.yaml, src/modules/iacm/Chart.yaml, src/modules/platform/Chart.yaml, src/modules/srm/Chart.yaml, src/modules/ssca/Chart.yaml, src/modules/sto/Chart.yaml
Reverts harness/helm-charts#974
=> Revert "feat: [PL-61236]: increment umbrella chart minor version for release/0.28.0"

src/docker-repo-map.yaml
Reverts harness/helm-charts#1009
=> Revert "add ff docker repo map changes"

src/harness/Chart.yaml, src/modules/ccm/Chart.yaml, src/modules/cd/Chart.yaml, src/modules/chaos/Chart.yaml, src/modules/ci/Chart.yaml, src/modules/code/Chart.yaml, src/modules/db-devops/Chart.yaml, src/modules/ff/Chart.yaml, src/modules/iacm/Chart.yaml, src/modules/platform/Chart.yaml, src/modules/srm/Chart.yaml, src/modules/ssca/Chart.yaml, src/modules/sto/Chart.yaml
This reverts commit 4bc23eb7fc8d268fb71fbf86bd776fd109af625d.
=> feat: [PL-63722]: Revert increment umbrella chart minor version for release/0.30.0

src/harness/Chart.yaml, src/modules/ccm/Chart.yaml, src/modules/cd/Chart.yaml, src/modules/chaos/Chart.yaml, src/modules/ci/Chart.yaml, src/modules/code/Chart.yaml, src/modules/db-devops/Chart.yaml, src/modules/ff/Chart.yaml, src/modules/iacm/Chart.yaml, src/modules/platform/Chart.yaml, src/modules/srm/Chart.yaml, src/modules/ssca/Chart.yaml, src/modules/sto/Chart.yaml
This reverts commit fdcaea543a5caec10bf760c00ef7ea43479fe77a.
=> feat: [PL-63722]: Revert increment umbrella chart minor version for release/0.30.0 
