src/prod/templates/ingress.yaml, src/prod/values.yaml
Adding values and objects alongside of Istio objects to support an already-installed NGINX ingress controller.
=> Add support for bring-your-own NGINX ingress controller

src/prod/templates/ingress.yaml, src/prod/values.yaml
Use the hosts field correctly, even in non-SSL installs; document IP-based install in values; standardize annotations indentation.
=> Use hosts correctly, document values for IP-based install

src/harness/Chart.lock, src/harness/Chart.yaml, src/harness/values.yaml, src/override-demo.yaml, src/override-prod.yaml
This PR has a dependancy on https://github.com/harness/helm-platform/pull/49, [PR](https://github.com/harness/helm-platform/pull/49) should be merged as well in order to add CHAOS module support.
In order to install CHAOS module, user needs to toggle the below fields to true in .Values.yaml they are using while helm installation -
```
global:
chaos:
enabled: true
```
By default, it will be set to `false`.
If you want to update some configuration values for chaos then it can be handled with the configuration updates as below -
```
chaos:
chaos-manager:
replicaCount: 1
resources:
limits:
cpu: 1500m
memory: 2048Mi
requests:
cpu: 1500m
memory: 2048Mi
chaos-driver:
replicaCount: 3
resources:
limits:
cpu: 500m
memory: 512Mi
requests:
memory: 512Mi
chaos-web:
replicaCount: 3
resources:
limits: …
```
=> feat[CHAOS-785]: add Chaos module support in SMP

src/harness/templates/ingress.yaml
Adding ingress rule for a new approvals openAPI in smp.
Tested in preqa and qa: [PR ](https://github.com/wings-software/ng-prod-manifests/pull/2953)
=> feat: [CDS-70575]: added ingress rule for approvals API in pipeline-service

src/harness/override-demo.yaml, src/harness/override-prod.yaml
Refer: [SMP 1268: Remove CPU from the resource limits in Kubernetes Manifests](https://harness.atlassian.net/wiki/spaces/~7120205e3981db61bd4dcc8068ae7262d845f7/pages/edit-v2/21404484175)
=> SMP-1268: Remove cpu from resources.limits for Redis

src/generate-image-list.sh, src/generate-image.yaml
Updated generate image script to avoid duplicate entries based on image name and tag.
Example of duplicates in old version:
docker.io/plugins/s3:1.2.3
plugins/s3:1.2.3
With new version, it will check for image name and tag, if its same, only add one entry.
Added enabled chaos module in yaml.
Tested locally, working as expected.
=> Updated generate image script to remove duplicate

src/harness/scripts/create-airgap-bundle.sh
Currrent airgap bundle script download binaries based on which arch machine is used to run the script.
This export DOCKER_DEFAULT_PLATFORM=linux/amd64 variable will make sure it always download amd64 architecture.
Tested locally
=> Added default env variable

.gitignore, src/harness/Chart.lock, src/harness/ci/Chart.lock, src/harness/infra/Chart.lock
Jira: https://harness.atlassian.net/browse/SMP-1555
- Removed Chart.lock file from Gitignore and ran "helm dependency update" for src/harness/ci, src/harness/infra and src/harness.
=> SMP-1555: remove chart.lock from gitignore

src/generate-image.yaml, src/harness/Chart.yaml, src/harness/override-demo.yaml, src/harness/override-prod.yaml, src/harness/templates/destinationrule.yaml, src/harness/values.yaml
The change introduces the Continuous Error Tracking as an independent module moving the error-tracking sub-charts to the new helm-cet repos. This removes the need for the "SRM" sub-chart dependencies
Note: SRM still has a global flag which enables the SRM related Feature Flags as cv-nextgen is installed as part of the platform chart.
=> feat: [CET-1354]: Initial CET commit. 

src/generate-image-list.sh
Follow-up for https://github.com/harness/helm-charts/pull/356 to fix missed hardcoded file paths.
=> SMP-1432: fix images list generation script

src/airgap/validate_airgap.sh
Validates each airgap bundle with its respective list of images.
Testing:
When tags don't match:
When all images match:
When number of images do not match:
=> Script for validating airgap bundle for correctness

src/harness/override-demo.yaml, src/harness/override-prod.yaml
Initially causing: 
after running migrate script, the error is resolved.
Tested templating locally.
=> fix:[SMP-2121]: Fix for invalidation errors in override files

src/harness/scripts/migrate-values-0.9.x.sh
Added support to put minimum yq version required for the migrate script
=> fix: [SMP-2128]: Add support to minimum yq version set field

src/airgap/harness-airgap-images.sh
Current harness image push script uses docker images command to list the images from tar file, this list also includes images from registry if its present. Causing redundant images being pushed in registry.
Solution: replaced docker images with docker load command.
Tested in local setup and escrow setup.
No more redundant images.
Output snippet:
Pushed: artifactory.harness.internal/cbp-docker/harness/ff-server-signed:1.1079.1
Finished processing ff_images.tgz
=> [SMP-2211] Fixed harness image push script with docker load

src/harness/override-prod.yaml
Removed duplicate keys for `cloud-info` and `event-service` from override-prod.yaml
=> fix: [SMP-2254]: removed duplicate keys

tests/config_test.yaml, tests/deployment_test.yaml, tests/hpa_test.yaml, tests/ingress_test.yaml, tests/pdb_test.yaml, tests/run_tests.sh, tests/service_test.yaml, tests/statefulset_test.yaml, tests/virtualService_test.yaml
This PR adds common unit tests for helm charts per template. It includes tests for deployment, service, ingress, statefulsets, virtualService, config, hpa and pdb.
=> Feat: [SMP-1834]: Adding common helm unit tests

src/harness/override-demo.yaml, src/harness/override-prod.yaml, src/harness/values.yaml
This PR removes the storage option in the override files for timescaledb and adds the correct PV option to set the data and wall sizes in override.
=> fix: [SMP-2303]: removing storage from timescaledb override and adding PV sizes correctly 

src/harness/values.yaml
waitForInit containers are now controlled by a common template function configurable at both global and service levels, with the service level having higher precedence.
Tested for multiple scenarios, refer to this: https://github.com/harness/harness-core/pull/57144#issuecomment-1885344654
=> fix: [SMP-2375]: Convert waitForInitContainers as global override

src/harness/configure-vality-url.sh
Via this script user can configure vanity url in smp
test:
Ran this script and then installed the URL and ran shell script pipeline
=> adding shell script to configure vanity url in smp

src/airgap/harness-airgap-images.sh
Adding functionality to pull looker image from private repo and push it to private registery for airgap
https://harness.atlassian.net/wiki/spaces/ONPREM/pages/21768667691/SMP+%3A%3A+Looker+migration+from+public+-%3E+private+repo
=> fix:[PL-51611]: fixing looker image pull and push to private registery

src/airgap/airgap_input.txt
move ubuntu and ng-dashbaord-aggregator to pl bundle
=> move ubuntu and ng-dashbaord-aggregator to pl bundle

src/harness/templates/_helper.tpl
- Currently, even we set seLinuxOptions to `null` or empty object {}, the field is still rendered by bitnami helper function and appears in the final security context.
- This causes problems where empty linux options is not allowed such as in gatekeeper policies
- This is a bug in bitnami chart and to fix it, we can have a function defined with same name as bitnami and omit the field if its empty.
=> fix: [PL-55757]: remove seLinuxOptions from bitnami rendered security context

src/harness/scripts/update-setting-parentUniqueId.sh
We are encountering an issue where the User Settings migration process is incorrectly identifying values for Account Settings, resulting in incorrect data population for existing settings. To address this, we need to:
- Remove the unique indexes associated with both fields.
- Clear the prefilled data to correct the inaccuracies.
- Reset the migration flag to enable a re-run of the migration with the correct parameters.
- Restart the NG Manager to execute the updated migration.
This process will ensure that the migration runs accurately and populates the settings correctly.
This need to be done for folk who updated to any of the following versions of SMP:
0.17.0 0.17.1 0.17.2 0.18.0 0.18.1 
If they are upgrading to 0.17.3 and 0.18.2 directly from 0.16.x or any lower version this would not …
=> Create update-setting-parentUniqueId.sh to re populate parentUniqueId with correct values

src/harness/values.yaml
We update the new delegate version in the harness-manager chart and then create a new patch release for the manager. This approach adds time to the overall sign-off pipeline runtime, making it difficult to release HF for delegate.
Moving the delegate version to the umbrella charts, this way we won’t have to re-build the harness-manager chart
Tested this locally with helm template command to validate the correct delegate image is coming in the final chart
Delegate version set in umbrella values.yaml file
Delegate version used in manager configmap
=> techdebt: [PL-56063]: moving delegate version to helm umbrella charts

src/harness/scripts/update-ingress-objects.sh
From 0.17.x There have been changes in Ingress object names for services, creating issues with upgrading for customers who are running Ingress/Nginx with Validation Webhook.
To mitigate this issue we are going ahead with a script-based approach which will update the ingress names before upgrading to any 0.17.x and above version
This script will take the namespace and upgrade version as input and based on that it will update the required ingress objects.
Testing
For testing, I set up a validation webhook and applied the new ingress manifests which failed. After that, I ran the script which updated the ingress objects and then the new ingress manifest was applied successfully.
Also tested the script with half of the services already upgraded and it only changed the remaining ones as …
=> [PL-56494]: Adding script to update ingress objects for validation webhook issue

tests/pdb_test.yaml
Since we changed pdb.yaml to get values from values.yaml. We need to set pdb.create : true to get pdb config in template and run tests on it.
=> feat: [PL-56709]: Update pdb_test.yaml

src/harness/scripts/update-ingress-objects.sh
Updating ingress script to include new changes in Ingress for 0.21.0
I have tested this by verifying the required service Ingress has been updated.
Difference between ingress names after running the update script on 0.20.2 charts
https://www.diffchecker.com/pEaCBJ5g/
Difference between ingress names after upgrading to 0.21.0 charts
https://www.diffchecker.com/nNGBYXBL/
The difference in ingress between 0.20.0 and 0.21.0 is based on the script (The script compares ingress between two manifests and tells the difference between them)
0.20.0 -> 0.21.0
1. next-gen-ui -> next-gen-ui-0
2. ng-dashboard-aggregator -> ng-dashboard-aggregator-0
3. service-discovery-manager -> service-discovery-manager-0
4. release-name-gitops -> gitops-http
5. chaos-manager -> chaos-manager-0
6. ng-auth-ui -> …
=> adding new ingress names for upgrade 0.21.0

src/harness/override-demo.yaml, src/harness/override-large.yaml, src/harness/override-medium.yaml, src/harness/override-perf.yaml, src/harness/override-prod.yaml, src/harness/override-small.yaml, src/harness/values.yaml
We have modified databases to use external secrets if enabled but this requires no top-level override in any values. This PR aims to remove the default secret name from postgres overrides so that the bootstrap template function can take effect.
=> fix: [PL-57424]: Remove default secret from postgres

src/harness/Chart.yaml
Add Kubeversion field to add min k8s supportable versions for helm-charts
When the versions (1.24.0) are not incompatible, it will give this error -
When using k8s version 1.29.0 -
=> feat: [PL-57969]: Add Kubeversion field to add k8s supportable versions for helm-charts

LICENSE.md
We need to add Apache 2.0 license because we are shipping mongo bitnami images, tsdb-oss etc which fall under apache 2.0 too.
◦ This needs to be done for helm-charts and smp airgap bundle
=> feat: [PL-58257]: Create License.Md for helm-charts and airgap bundle

src/harness/scripts/update-ingress-objects.sh
Adding comparison of 0.22.0 & 0.23.0 ingress objects
=> update ingress name script for 0.23.0

src/harness/override-perf.yaml
In order to achieve best performance, some settings are needed on both log-service and ci-manager.
=> fix: [PIPE-0]: Perf - Update override-perf.yaml

tests/pdb_test.yaml
If a local value is set in the service, as seen in this PR - https://harness0.harness.io/ng/account/l7B_kbSEQD2wjrM7PShm5w/module/code/orgs/PROD/projects/Harness_Commons/repos/harness-core/commit/664cf250d6ff3faaef1f2da9ea8e6633491670fb
, it will cause tests that assume no preset value to fail.
To ensure the tests verify the default values and overrides correctly, explicitly set the local values to empty within the test setup.
=> fix: [PL-10000]: pdb ut fix

src/harness/values.yaml
Few months back, we introduced headless services for GRPC loadbalancing. The clients used dns URLs to get server endpoints and do round robin loadbalancing for GRPC connections. This doesn't work with istio proxy. This PR aims to use regular service domains if istio is enabled.
=> fix: [PL-61323]: use service domain instead of headless service for istio

src/harness/templates/mongo-preupgradejob.yaml
use external secrets if configured for mongo fcv job
=> fix: [PL-61162]: use external secrets if configured for mongo fcv job
